;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname img-handin) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(require 2htdp/image)
(define TASK-1-A
  (* (* (* (* (- 2015 1986) 365) 24) 60) 60))
(define TASK-1-B (* (/ 20.50 1.19) 1.07))
(define TASK-1-C (* (+ 17 32 6 7 4) (/ 1 4)))
(define TASK-1-D (+ (* (+ (- 14 (* 9 8)) 4) 5.5) 22))
(define TASK-1-E 1)
(define TASK-2-A (+ 2 (- 12 8)))
(define TASK-2-B (+ 42 0))
(define TASK-2-C (rectangle 40 30 "solid" "darkorange"))
(define TASK-2-D (place-image (circle 10 120 "white") 25 25 (rectangle 50 50 110 "red")))
(define TASK-2-E (string-append "The answer is " (number->string 42)))
(define TASK-3 (circle 20 "solid" "red"))
(define a 2)
(check-expect a 2)
(check-expect (+ a 1) 3)
(check-expect (+ a 1) 3)
(check-expect (+ a 1) 3)
(check-expect (+ a 1) 3)